name: action-test
on:
  push
defaults:
  run:
    shell: bash
    working-directory: scripts
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: step1
    run: touch 1.md
    