name: action-test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
defaults:
  run:
    shell: bash
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config_env
        run: |
          sudo apt-get install pandoc
        #wget -qO- "https://yihui.org/gh/tinytex/tools/install-unx.sh" | sh
        #tlmgr install unicode-math filehook xecjk xltxtra realscripts fancyhdr lastpage ctex ms cjk ulem environ trimspaces zhnumber collection-fontsrecommended
      - name: md2pdf
        run: |
#pandoc 1.md -o 1.pdf --pdf-engine=xelatex -V mainfont='PingFang SC' --template=template.tex
          pandoc --version
      - name: commit
        run: |
          git config --global user.email 2066729323@qq.com
          git config --global user.name github_actions
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
