name: action-test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
defaults:
  run:
    shell: bash
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step1
        run: |
          git init
          git remote add origin https://github.com/jwb528/github-actions-test.git
          touch 1.md
          git add .
          git commit -am "1"
          git push origin
