name: action-test
on: push
defaults:
  run:
    shell: bash
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo "123">>123.md
      - name: commit
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com>"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}