name: action-test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
defaults:
  run:
    shell: bash
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test_PATH
        run: echo $PATH
      - name: edit_bashrc
        run: |
          sudo echo "export PATH=$PATH:$HOME/bin">>~/.bashrc
          source ~/.bashrc 
          cat ~/.bashrc
          echo $PATH
      - name: test_PATH
        run: echo $PATH
      - name: commit
        run: |
          git config --global user.email 2066729323@qq.com
          git config --global user.name github_actions
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
